FC out1.txt C:\Test_cases\Test_cases\TA_output1.txt
FC out2.txt C:\Test_cases\Test_cases\TA_output2.txt
FC out3.txt C:\Test_cases\Test_cases\TA_output3.txt
FC out4.txt C:\Test_cases\Test_cases\TA_output4.txt
FC out5.txt C:\Test_cases\Test_cases\TA_output5.txt
FC out6.txt C:\Test_cases\Test_cases\TA_output6.txt
FC out7.txt C:\Test_cases\Test_cases\TA_output7.txt
FC out8.txt C:\Test_cases\Test_cases\TA_output8.txt
FC out9.txt C:\Test_cases\Test_cases\TA_output9.txt
FC out10.txt C:\Test_cases\Test_cases\TA_output10.txt
FC out11.txt C:\Test_cases\Test_cases\TA_output11.txt
FC out12.txt C:\Test_cases\Test_cases\TA_output12.txt
FC out13.txt C:\Test_cases\Test_cases\TA_output13.txt
FC out14.txt C:\Test_cases\Test_cases\TA_output14.txt
FC out15.txt C:\Test_cases\Test_cases\TA_output15.txt
FC out16.txt C:\Test_cases\Test_cases\TA_output16.txt
FC out17.txt C:\Test_cases\Test_cases\TA_output17.txt
FC out18.txt C:\Test_cases\Test_cases\TA_output18.txt
FC out19.txt C:\Test_cases\Test_cases\TA_output19.txt
FC out20.txt C:\Test_cases\Test_cases\TA_output20.txt
