java ModelMatcher C:\Test_cases\Test_cases\testcase1 > out1.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase2 > out2.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase3 > out3.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase4 > out4.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase5 > out5.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase6 > out6.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase7 > out7.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase8 > out8.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase9 > out9.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase10 > out10.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase11 > out11.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase12 > out12.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase13 > out13.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase14 > out14.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase15 > out15.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase16 > out16.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase17 > out17.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase18 > out18.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase19 > out19.txt
java ModelMatcher C:\Test_cases\Test_cases\testcase20 > out20.txt
